### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by hitimo** [jmbuena/img_align_lib#3]
In https://github.com/jmbuena/img_align_lib/blob/master/src/test_img_align.cpp#L43
should be
`#elif defined(USE_HOMOGRAPHY_FACTORIZED_PROBLEM)`
instead of
`#elif defined(USE_HOMOGRAPHY_cv::INTER_NEAREST;FACTORIZED_PROBLEM)`

**Comment by jmbuena** [comment]
Now fixed.
